### ISSUE TITLE
Get a GF license

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/gravity-forms-stubs#1]
Hello @sebkay! 👋🏻 

Would you contact GF developers to get a license for these stubs?
https://www.gravityforms.com/open-support-ticket/account/

**Comment by szepeviktor** [comment]
...maybe it is beneficial to tell them that stubs are empty function declarations without actual source code

**Comment by SebKay** [comment]
I'll get in touch and let you know what they say.

**Comment by SebKay** [comment]
Have contacted them. Will report back soon as I hear something.

**Comment by szepeviktor** [comment]
When you have the license key we should figure out the [download URL/method](https://github.com/szepeviktor/debian-server-tools/blob/8229be3024c4bfe4ec2a3be8068b8170d2394ad0/webserver/wordpress/_core-http.php#L27-L39).

**Comment by justlevine** [comment]
If this is blocker for CI, I am happy to store my developers license key as a repo secret.

If it's a blocker for development, I'm happy to set up a private repo that auto-pushes new releases, and give ya'll team access (where you can add others working on the project).

> When you have the license key we should figure out the [download URL/method](https://github.com/szepeviktor/debian-server-tools/blob/8229be3024c4bfe4ec2a3be8068b8170d2394ad0/webserver/wordpress/_core-http.php#L27-L39).

@szepeviktor I'm not entirely sure what that file you referenced does, but If you mean the ideal way to pull new GF versions from the source, the most stable way I've found is using GF's cli ([e.g](https://github.com/harness-software/wp-graphql-gravity-forms/blob/develop/bin/_lib.sh#L103-L133)). There is AFAIK no way to request a non-current version, which shouldnt be a problem as GF doesnt release patches on old major/minor branches, but if that's essential we could use my suggestion of a private repo instead.

**Comment by szepeviktor** [comment]
@justlevine There is no Composer package that runs WordPress + WP-CLI :(

`ffraenz/private-composer-installer` could execute a simple HTTP GET request.
Simply install/upgrade that plugin and look for the URL:
https://github.com/szepeviktor/debian-server-tools/blob/8229be3024c4bfe4ec2a3be8068b8170d2394ad0/webserver/wordpress/_core-http.php#L27-L39

**Comment by szepeviktor** [comment]
You can trace things from here on
https://plugins.trac.wordpress.org/browser/gravityformscli/trunk/includes/class-gf-cli-root.php#L350

**Comment by justlevine** [comment]
> There is no Composer package that runs WordPress + WP-CLI :(

Is that a prerequisite vs a bash script?

I personally find `ffraenz/private-composer-installer` a PITA to use for versioning (since you need to manually know there was a new release, and then update the composer), but either way 🤷‍♂️

Lemme know re the repo licence secret and/or a private repo

**Comment by szepeviktor** [comment]
> Lemme know re the repo licence secret and/or a private repo

So we won't have a license granted for this project only?

**Comment by justlevine** [comment]
Correct, it's my personal license. I'm offering it in secret form (or as an autoversioned plugin repo) as either a temporary solution until @SebKay gets a response from GF support, or a long term one if they're unwilling to donate one. Whichever helps development on these stubs progress 😎

While the Elite license allows me to use it on as many projects as I want, to my understanding it still forbids me from sharing the license itself with others.

**Comment by szepeviktor** [comment]
All right. I see.

I'm sorry but I have policies which are more important to me than apparent project "success".
I go and open a ticket at GF Support... 🏃🏻‍♂️

**Comment by szepeviktor** [comment]
Done.

> Good afternoon!
> 
> I run a project that distributes stubs for WordPress with few million downloads: https://github.com/php-stubs
> 
> Would you be interested in distributing stubs for Gravity Forms plugin?
> https://github.com/php-stubs/gravity-forms-stubs/issues/1
> 
> If yes, please grant me a license that would be stored as a GitHub Actions secret.
> 
> What do you think?
> All the best to you!
>

**Comment by szepeviktor** [comment]
>  Our records indicate we provided a 1-year license for use with https://github.com/php-stubs in September. I'm not very familiar with how your project is organized, but you might check in with the other contributors to gain access to the license. I hope this info is helpful!

@SebKay Could you please email me the key? viktor@szepe.net

**Comment by szepeviktor** [comment]
@justlevine We have the license key.

![kép](https://user-images.githubusercontent.com/952007/197338777-b7ecb195-4bc0-46f4-8274-5ed8f896522b.png)

You can start working.

**Comment by szepeviktor** [comment]
@justlevine What is your ETA for starting?

**Comment by justlevine** [comment]
@szepeviktor in middle of some client deadlines but hopefully after the 15th 🤞

**Comment by szepeviktor** [comment]
All right. I can't stop Viktor from doing it!

**Comment by szepeviktor** [comment]
@SebKay @justlevine Would you like to contribute?

**Comment by crbon** [comment]
Any update?

**Comment by szepeviktor** [comment]
No.

**Comment by szepeviktor** [comment]
@crbon Would you like to contribute?

**Comment by szepeviktor** [comment]
@crbon This is the first release.
v2.6.7 🎉 

I cannot find a GF API that gives me older releases.
Could you help?
