### ISSUE TITLE
Preparing file list for generator

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/gravity-forms-stubs#2]
https://github.com/php-stubs/wordpress-stubs/blob/master/finder.php

@SebKay I think GF is a huge mess even compared to other products in the WordPress ecosystem.
In php-stubs org I follow a rule that deprecated and compatibility parts should be excluded from stubs.
There are class files with side-effects 🤯 `new GFFormLocking();` ... and multiple classes in 1 file.
PHPStan on Level 0 says _Found 131 errors_

Could you look around in the GF plugin for included/excluded files/directories?

**Comment by SebKay** [comment]
I would recommend not running PHPStan on Gravity Forms, it's definitely a bit of a mess.

I've had a look but couldn't see anything obvious. The `gravityforms.php` file is 7000+ lines long haha

**Comment by szepeviktor** [comment]
My looking around results in:

- the includes/ directory
- *.php files in the plugin root

**Comment by szepeviktor** [comment]
Two rgar-s!

```bash
sed -i -e 's#^\(\s*function \)\(rgar(.*\)$#\1__\2#' source/gravityforms/xml.php
```

**Comment by szepeviktor** [comment]
/finder.php

```php
<?php

return \StubsGenerator\Finder::create()
    ->in('source/gravityforms/includes')
    ->append(
        \StubsGenerator\Finder::create()
            ->in(['source/gravityforms'])
            ->files()
            ->depth('< 1')
            ->name('*.php')
    )
    ->sortByName()
;
```

output:
```
 ----------- --------- ------------ -------- ----------- ---------
  functions   classes   interfaces   traits   constants   globals
 ----------- --------- ------------ -------- ----------- ---------
  31          256       2            1        0           0
 ----------- --------- ------------ -------- ----------- ---------
```

**Comment by szepeviktor** [comment]
Completed.
https://github.com/php-stubs/gravity-forms-stubs/blob/master/finder.php
