### ISSUE TITLE
Invalid PHPDoc blocks

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/gravity-forms-stubs#4]
https://github.com/php-stubs/acf-pro-stubs/blob/7e44b653bd72e5eebf725f3af6b5afaae3039dcf/generate.sh#L30-L43

There are ~100 invalids only from this type-less param type.

`grep -r '@param\s*\$' | wc -l`

**Comment by szepeviktor** [comment]
Fixing 369 invalid `@param` tags require several days of work from GF authors.

**Comment by szepeviktor** [comment]
Is it a good ide to replace
`@param $entry` 👉🏻 `@param mixed $entry`??

**Comment by justlevine** [comment]
> Is it a good ide to replace `@param $entry` 👉🏻 `@param mixed $entry`??

afaik an `$entry` is always either an array or _some_ falsy (`null | false | ''` ), depending on the particular method. No need to go full `mixed`.

**Comment by szepeviktor** [comment]
But this is an **automatic** repo. No one will fix it manually for every release :(

Is `mixed` better than an invalid docblock? (theoretic question)
I am not planning to spend time on this repo.

**Comment by justlevine** [comment]
Sorry I wasn't clear. I think `mixed` is better than an **invalid** docblock, but specifically for `$entry`, you should be able to string-replace to `@param array|string|false|null $entry`.

**Comment by szepeviktor** [comment]
GF's code quality is abysmally low. It has no API to serve older releases.
This is money making and targeting non-experts only.
So I am out.

**Comment by szepeviktor** [comment]
Please see https://community.gravityforms.com/t/new-package-gravity-forms-stubs-for-ide-autocompletion-and-static-analysis/15577
