### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by justlevine** [php-stubs/gravity-forms-stubs#5]
Hey @szepeviktor,

I was planning on attempting my own release of GF + extension stubs, but I'd much rather contribute to an existing /official project. 
Is this repo something you're still working on (i see open issue, but no code), and if so how can I help?

**Comment by szepeviktor** [comment]
> official

❤️

**Comment by szepeviktor** [comment]
> How to contribute?

Tell me your plans on open issues and you get maintainer role!

**Comment by szepeviktor** [comment]
Find a GF API that gives me older releases.
