### ISSUE TITLE
README

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/gravity-forms-stubs#6]
@justlevine Please add a "thank you for the license" section to the top of README

**Comment by justlevine** [comment]
Id be happy to. Is there an existing codebase I should be working from (for the readme and in general) or should I just fork a readme from one of the other php-stubs projects?

**Comment by szepeviktor** [comment]
It is up to you.
php-stubs org has no rules :)

Please work in PR-s.

---

Pinned.
![kép](https://user-images.githubusercontent.com/952007/197349350-3b173518-ab5a-4ccb-9cab-0f86978e0621.png)

**Comment by szepeviktor** [comment]
e.g. you can talk about usage: static analysis and IDE autocomplete
https://github.com/php-stubs/woocommerce-stubs/blob/master/README.md

**Comment by szepeviktor** [comment]
@justlevine Please consider contributing a README.
