### ISSUE TITLE
Stubs file is too big

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/gravity-forms-stubs#7]
Directory sizes
```
88  orders
92  system-status
96  legacy
96  query
108 locking
128 phpqrcode
320 settings
444 webapi
632 addon
672 splash-page
760 fields
```

Maybe distribute fields in a separate stubs file??

**Comment by szepeviktor** [comment]
> Maybe distribute fields in a separate stubs file??

Only 1.2 MB -> 1.0 MB reduction.

**Comment by mikemanger** [comment]
I wonder if it would be beneficial (or possible) to generate a stubs file with only the unnamespaced items and whatever namespaced things they rely on.

As far as I can tell a lot of the namespaced items aren't intended for regular developer use - one exception being the "[Theme Framework](https://docs.gravityforms.com/theme-layers-view-classes/)" (`Gravity_Forms\Gravity_Forms\Theme_Layers\API\**`) but even that is so specific it could be spun out into its own stubs file.
