### ISSUE TITLE
Downloading plugin ZIP in CI

### ISSUE THREAD

**Issue by szepeviktor** [php-stubs/gravity-forms-stubs#8]
```
https://gravityapi.com/wp-content/plugins/gravitymanager/api.php?op=get_plugin&slug=gravityforms&key=$PLUGIN_GF_KEY
```

the response is a serialized PHP array

```php
$i=unserialize(stream_get_contents(STDIN));
echo $i["download_url"];
```

Signed URL: `https://s3.amazonaws.com/gravityforms/releases/gravityforms_2.6.7.zip?....`

**Comment by szepeviktor** [comment]
```
url(
  scheme:  'https'
  host:    's3.amazonaws.com'
  path:    '/gravityforms/releases/gravityforms_2.6.7.zip'
  query(
    AWSAccessKeyId: '***'
    Expires: '***'
    Signature: '***'
  )
)
```

I think we should put the URL into an environment variable and feed it into `ffraenz/private-composer-installer`

`GF_SIGNED_URL`

**Comment by szepeviktor** [comment]
All the above could be done in PHP.

- check for `PLUGIN_GF_KEY`
- make the API request
- check response status and `download_url`
- set up a Composer command with `GF_SIGNED_URL` environment variables - `putenv`
- execute the command - `system`

**Comment by szepeviktor** [comment]
We need a GF API that gives us older releases.

**Comment by justlevine** [comment]
I'm fairly certain they dont host releases older than 2.6.x...

**Comment by szepeviktor** [comment]
All right.
Then I will release a new version when someone asks for it.
