### ISSUE TITLE
signature and DocBlock for gf_apply_filters() is incorrect

### ISSUE THREAD

**Issue by pbiron** [php-stubs/gravity-forms-stubs#9]
I figure you generate the stubs in this package by running the [PHP Stubs Generator](https://github.com/php-stubs/generator) on the latest GF code.

This is a difficult one.  GF defines this function to only have 2 args (`$filter` and `$value`), which is reflected in the stub.

However, the function calls `func_get_args()` to get additional arguments (up to 9 of them).  GF **should** change the function definition (and it's DocBlock) to use the variadic `...` token.  I don't know why they haven't done so.

For the time being, I have modified the stubs installed for one my GF addon plugins that calls `gf_apply_filters()` as be follows:

```
    /**
     * Gravity Forms pre-processing for apply_filters
     *
     * Allows additional filters based on form and field ID to be defined easily.
     *
     * @since  Unknown
     * @access public
     *
     * @param string|array $filter The name of the filter.
     * @param mixed $value The value to filter.
     * @param mixed ...$additional_args Additional arguments.
     *
     * @return mixed The filtered value.
     */
    function gf_apply_filters($filter, $value, ...$additional_args)
    {
    }
```

I'm sure it would be too much trouble for you to manually modify the generated stubs that you generate every time a new version of GF is released.  But I just wanted to open this issue to raise the possibility.

**Comment by szepeviktor** [comment]
> I'm sure it would be too much trouble for you

Thank you for your report!
I am glad that you use these stubs in your work.

What method do you suggest to apply fixes?
Have you nagged Rocketgenius?

**Comment by szepeviktor** [comment]
One more thing: you could override these stubs in an other stubs file.

**Comment by pbiron** [comment]
> Thank you for your report! I am glad that you use these stubs in your work.

thanx for the quick reply.  I've only recently started using phpstan and your work on both stubs and `phpstan-wordpress` certainly makes using phpstan much easier than it would otherwise be.

> What method do you suggest to apply fixes? Have you nagged Rocketgenius?

For the time being, I suggest you not do anything ;-)  As I said, I'm OK with my local fix for now.

No, but I will do so tomorrow (and will reference this issue when I open a ticket with them).  When I hear back from RG I'll add their reply to this issue.

**Comment by pbiron** [comment]
> One more thing: you could override these stubs in an other stubs file.

How would I do that?  As mentioned above, I'm very new to using phpstan.  If I add a custom stub file in `phpstan.neon` with just the decl I gave above **after** I load these stubs will phpstan use the 2nd DocBlock?

**Comment by szepeviktor** [comment]
> **after** I load these stubs will phpstan use the 2nd DocBlock?

Try after and before!

**Comment by pbiron** [comment]
**after** didn't work, but **before** does the trick, thanx!

I'll let you know when I hear back from RG.
